//******************************************************************
// Sample program
// This program computes the square and cube of 27
//******************************************************************
#include <iostream>
using namespace std;

int Square( int ); //function prototype
float Cube( float );


int main()
{
    cout << "The square of 13 is " << Square(13) << endl;
    cout << "and the cube of 13 is " << Cube(13) << endl;
   // system("PAUSE");
    return 0;
}
//function definition
int Square( int n )
{
    return n * n;
}

float Cube( float n )
{
    return n * n * n;
}

int sujan()
{




}
